### PR TITLE
More spatie packages

### PR DESCRIPTION
**Pull request by krekas**

### CODE REVIEW

**Comment by Elnadrion** [comment]
https://github.com/spatie/laravel-health is a gr8 package too. I use it with Zabbix or with K8S Liveness Probes

**Comment by PovilasKorop** [comment]
@krekas great job! I will go through the list and comment on some packages. Keep in mind the goal here is not to add as many packages as possible, but to emphasize the best and most commonly used ones, so I would qualify some packages as too "niche" and "edge case" and they better give their place in the list to the more in-demand packages. Of course, it's based on my personal opinion, and anyone can debate, but I have a vision of what such a "best packages" list should look like.

With that in mind, my comments:

- https://github.com/spatie/laravel-fractal - I would take it OFF the list, because with Laravel API Resources, not too many people use Fractal, from what I see in the community
- https://github.com/spatie/laravel-event-sourcing - event sourcing is too niche, also please remove from the list
- https://github.com/spatie/laravel-route-attributes - this one is highly opinionated and was released almost like an experiment, I would also remove it
- https://github.com/spatie/laravel-view-models - interesting concept but it kinda goes against a typical MVC approach so I wouldn't want to advise too many people to stick to this approach, remove from the list
- https://github.com/spatie/laravel-newsletter - this is more like an application than a package, and also quite niche topic, remove from the list

Also, I see we can re-group some packages or create new sections, but let's do it after more packages are added.

**Comment by PovilasKorop** [comment]
@Elnadrion great package indeed, but I chose the lower limit of 500 Github stars minimum for packages to be on this list. I know it's a bit silly number, but that show how many people actually are interested in the package, and I want to showcase the BEST ones. So laravel-health, at least for now, doesn't make this list. Also, it has not many checks by default, you basically need to create your own checks to make it actually useful, so this package is more like a framework.

**Comment by krekas** [comment]
@PovilasKorop I removed those packages.

**Pull request merged**
